### PR TITLE
Fix combine tests with Accumulation Mode

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:
- [ ] Make sure the PR title is formatted like:
  `[BEAM-<Jira issue #>] Description of pull request`
- [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
     Travis-CI on your fork and ensure the whole test matrix passes).
- [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
     number, if there is one.
- [ ] If this contribution is large, please file an Apache
     [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

These tests were not written in such a way as to succeed if the trigger
fired multiple times.

### CODE REVIEW

**Comment by aljoscha** [comment]
Thanks for fixing these!

One question, though. I was assuming, that if you use `ACCUMULATING` then the window contents will be emitted one last time if there is any new data at garbage collection time. It seems that this is wrong and that on cleanup time we only emit if there is new data AND if the trigger is not finished AND if the trigger indicates that we can fire. Is that correct?

**Comment by aljoscha** [comment]
Hmm, it still doesn't work. `PAssert.that(output).satisfies` seems to also expects to get just one pane.

**Comment by aljoscha** [comment]
Btw, the reason is the check in here:

```
  private static class ExtractOnlyPane<T>
      extends SimpleFunction<Iterable<WindowedValue<T>>, Iterable<T>> {
    @Override
    public Iterable<T> apply(Iterable<WindowedValue<T>> input) {
      List<T> outputs = new ArrayList<>();
      for (WindowedValue<T> value : input) {
        checkState(value.getPane().isFirst() && value.getPane().isLast(),
            "Expected elements to be produced by a trigger that fires at most once, but got"
                + "a value in a pane that is %s. Actual Pane Info: %s",
            value.getPane().isFirst() ? "not the last pane" : "not the first pane",
            value.getPane());
        outputs.add(value.getValue());
      }
      return outputs;
    }
  }
```

in PaneExtractors.java which is used when `PAssert.that(output).satisfies(...)` is used.

Can this check be removed?

**Comment by tgroh** [comment]
The check is appropriate for the pane extractor; the pane extractor is the wrong choice for the default `IterableAssert`; we should instead be using `allPanes`

I've pushed an update to fix that.

**Comment by tgroh** [comment]
On `Accumulating` mode: If the trigger is not `FINISHED`, we will emit a final pane at GC time. However, the **current** behavior is that if the trigger is `FINISHED`, we will drop incoming elements.

**Comment by aljoscha** [comment]
Perfect! All the tests are passing now. And thanks for the clarification.

**Pull request closed without merging**
